#### Required Python Libraries

In [1]:
import numpy as np
import pickle
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import plotly.graph_objects as go
import warnings
warnings.filterwarnings('ignore')

#### Model Testing

##### Loading the Scaler model pickle file

In [2]:
with open('Scaler.pkl','rb') as scaler_model_file :
    ss = pickle.load(scaler_model_file)

##### Loading the model pickle file

In [3]:
with open('ANN_Model.pkl','rb') as ann_model_file :
    model = pickle.load(ann_model_file)

##### Loading the saved testing sets

In [4]:
x_test = np.load('x_test.npy')
y_test = np.load('y_test.npy')

##### Standardization of testing set

In [5]:
x_test_scaled = ss.transform(x_test)
x_test_scaled

array([[ 0.98640353,  2.28524509,  1.03898144, ..., -1.49123331,
        -1.31573637, -0.34154137],
       [-1.01378388, -0.43758982, -0.9624811 , ..., -1.49123331,
        -1.32567961, -0.79891621],
       [ 0.98640353, -0.43758982,  1.03898144, ..., -0.55085356,
         1.2446468 , -0.40456894],
       ...,
       [-1.01378388, -0.43758982, -0.9624811 , ...,  1.32990594,
        -0.28661148, -0.31882496],
       [-1.01378388,  2.28524509, -0.9624811 , ..., -1.49123331,
         1.52802902,  0.68921878],
       [-1.01378388, -0.43758982,  1.03898144, ..., -1.49123331,
        -1.31242196, -0.18431463]])

##### Predicting the values with the help of test values

In [6]:
pred = model.predict(x_test_scaled)

44/44 [==============================] - 0s 676us/step


##### Predicting the labels

In [7]:
y_pred = np.where(pred < 0.5,0,1)
y_pred

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

##### Making the DataFrame for storing the Actual Labels as well as Predicted Labels

In [8]:
comp = pd.DataFrame()
comp['Actual Labels'] = y_test
comp['Predicted Labels'] = y_pred
comp.sample(10)

Actual Labels  Predicted Labels
408               0                 0
677               0                 0
478               1                 0
161               0                 0
964               0                 0
1323              0                 0
96                0                 0
742               0                 0
137               1                 1
203               0                 0

In [20]:
sam = pd.DataFrame(x_test)
pd.set_option('display.max_columns', None)
sam['True'] = y_test
sam['Prediction'] = comp['Predicted Labels']
sam

0    1    2    3     4    5    6    7    8    9   10   11   12   13  \
0     1.0  1.0  1.0  0.0  61.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0   
1     0.0  0.0  0.0  0.0  19.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0   
2     1.0  0.0  1.0  0.0  13.0  1.0  2.0  1.0  0.0  0.0  2.0  0.0  2.0  2.0   
3     1.0  0.0  1.0  0.0  37.0  1.0  2.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0   6.0  0.0  1.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0   
...   ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1402  1.0  0.0  0.0  0.0   1.0  1.0  0.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0   
1403  1.0  0.0  0.0  0.0  12.0  1.0  2.0  1.0  0.0  0.0  0.0  0.0  2.0  2.0   
1404  0.0  0.0  0.0  0.0  26.0  1.0  0.0  0.0  0.0  2.0  2.0  0.0  0.0  0.0   
1405  0.0  1.0  0.0  0.0  35.0  1.0  2.0  1.0  2.0  2.0  2.0  2.0  2.0  2.0   
1406  0.0  0.0  1.0  1.0  72.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0   

       14   15   16      17       18  True  Prediction  
0     2.0  0.0  0.0   25.00  1501.75     0           0  
1     0.0  0.0  0.0   24.70   465.85     0           0  
2     0.0  1.0  1.0  102.25  1359.00     1           1  
3     0.0  1.0  3.0   55.05  2030.75     0           0  
4     0.0  0.0  0.0   29.45   161.45     0           0  
...   ...  ...  ...     ...      ...   ...         ...  
1402  0.0  0.0  3.0   19.05    19.05     0           0  
1403  0.0  0.0  2.0   94.55  1173.55     0           1  
1404  1.0  1.0  3.0   56.05  1553.20     0           0  
1405  1.0  1.0  0.0  110.80  3836.30     0           0  
1406  2.0  0.0  0.0   25.10  1857.85     0           0  

[1407 rows x 21 columns]

In [16]:
sam[sam['True']==sam['Prediction']]

0    1    2    3     4    5    6    7    8    9  ...   11   12   13  \
0     1.0  1.0  1.0  0.0  61.0  1.0  2.0  2.0  1.0  1.0  ...  1.0  1.0  1.0   
1     0.0  0.0  0.0  0.0  19.0  1.0  2.0  2.0  1.0  1.0  ...  1.0  1.0  1.0   
2     1.0  0.0  1.0  0.0  13.0  1.0  2.0  1.0  0.0  0.0  ...  0.0  2.0  2.0   
3     1.0  0.0  1.0  0.0  37.0  1.0  2.0  0.0  2.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0   6.0  0.0  1.0  0.0  2.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1401  1.0  0.0  0.0  0.0   1.0  1.0  2.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1402  1.0  0.0  0.0  0.0   1.0  1.0  0.0  2.0  1.0  1.0  ...  1.0  1.0  1.0   
1404  0.0  0.0  0.0  0.0  26.0  1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
1405  0.0  1.0  0.0  0.0  35.0  1.0  2.0  1.0  2.0  2.0  ...  2.0  2.0  2.0   
1406  0.0  0.0  1.0  1.0  72.0  1.0  2.0  2.0  1.0  1.0  ...  1.0  1.0  1.0   

       14   15   16      17       18  True  Prediction  
0     2.0  0.0  0.0   25.00  1501.75     0           0  
1     0.0  0.0  0.0   24.70   465.85     0           0  
2     0.0  1.0  1.0  102.25  1359.00     1           1  
3     0.0  1.0  3.0   55.05  2030.75     0           0  
4     0.0  0.0  0.0   29.45   161.45     0           0  
...   ...  ...  ...     ...      ...   ...         ...  
1401  0.0  1.0  2.0   50.45    50.45     1           1  
1402  0.0  0.0  3.0   19.05    19.05     0           0  
1404  1.0  1.0  3.0   56.05  1553.20     0           0  
1405  1.0  1.0  0.0  110.80  3836.30     0           0  
1406  2.0  0.0  0.0   25.10  1857.85     0           0  

[1092 rows x 21 columns]

#### Model Evaluation

##### Calculating the accuracy score of the model

In [11]:
print(f"Accuracy Score of the Model : {accuracy_score(y_test,y_pred)*100:.2f}%")

Accuracy Score of the Model : 77.61%


##### Calculating the confusion matrix of the model

In [12]:
cm = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix of the Model :")
print(cm)

Confusion Matrix of the Model :
[[910 123]
 [192 182]]


##### Plotting the confusion matrix

In [13]:
fig = go.Figure(data=go.Heatmap(z=cm,colorscale='Viridis'))
fig.update_layout(title='Confusion Matrix',
                  xaxis=dict(title='Predicted Label'),
                  yaxis=dict(title='True Label'))
fig.show()

##### Displaying the classification report of the model

In [14]:
print("Classification Report of the Model :")
print(classification_report(y_test,y_pred))

Classification Report of the Model :
              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1033
           1       0.60      0.49      0.54       374

    accuracy                           0.78      1407
   macro avg       0.71      0.68      0.69      1407
weighted avg       0.76      0.78      0.77      1407

